# Aider configuration

# Specify the OpenAI model to use
model: "gpt-4o"

# OpenAI API key
openai-api-key: "sk-None-q0FV44b8QTRIWPWvZNvGT3BlbkFJMT0mc85DVqkpDWe6Yc4X"


# GUI mode
gui: true

# Show diffs when committing changes
show-diffs: true



########################
# Additional Behavior Settings:

# To enforce succinct responses
stream: true # Streams the assistant's response, which often makes it more concise

# Disable auto-linting, testing, and other automatic features
auto-lint: false
auto-test: false

# Avoid auto-commits if you only want to review changes first
auto-commits: false

