version: '3.9'

services:
  web:
    image: kosielemmer/filamento:latest
    ports:
      - "8090:8090"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./app.py:/app/app.py
      - filament_data:/data
    restart: unless-stopped

volumes:
  filament_data:
