version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: filament-inventory-app:latest
    ports:
      - "0.0.0.0:8090:8090"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./app:/app
    restart: unless-stopped

  build_logger:
    image: bash:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["bash", "build_and_log.sh"]
